name: jetbrains-toolbox
title: Manage your IDEs the easy way
base: core24
version: 3.2.0.65851
summary: JetBrains Toolbox App
description: JetBrains Toolbox packaged as a Snap.
license: MIT
type: app
icon: snap/gui/icon.svg
website: https://www.jetbrains.com/toolbox-app/
source-code: https://github.com/jnsougata/jetbrains-toolbox-snap
contact: jnsougata@gmail.com

grade: stable
confinement: classic

apps:
  jetbrains-toolbox:
    command: src/jetbrains-toolbox
    desktop: jetbrains-toolbox.desktop
    plugs:
      - network
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl

parts:
  jetbrains-toolbox:
    plugin: dump
    source: .
