name: jetbrains-toolbox
base: core24
version: 3.2.0.65851
summary: JetBrains Toolbox App
description: JetBrains Toolbox packaged as a Snap.
license: MIT
type: app
icon: snap/gui/icon.svg


grade: devel
confinement: classic

apps:
  jetbrains-toolbox:
    command: src/jetbrains-toolbox
    desktop: jetbrains-toolbox.desktop
    plugs:
      - network
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl

parts:
  jetbrains-toolbox:
    plugin: dump
    source: .
